name: Build, Test, and Release C++ Backup Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Grant permissions to modify repository contents, including creating releases.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libzip-dev nfs-common

    - name: Compile C++ code
      run: |
        g++ -std=c++17 -o backup_tool backup_tool.cpp -lzip

    - name: Upload compiled executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: backup_tool
        path: backup_tool

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download compiled executable
      uses: actions/download-artifact@v4
      with:
        name: backup_tool

    - name: Create a new tag
      id: tag_version
      run: |
        TAG_VERSION="v1.0.${{ github.run_number }}"
        git tag $TAG_VERSION
        git push origin $TAG_VERSION

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: backup_tool
        tag_name: ${{ steps.tag_version.outputs.TAG_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
